# Generated by Django 2.2.11 on 2020-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_requestlog_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='log',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.CharField(default='GET', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlog',
            name='status_code',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
